version: '3.8'
services:
  db:
    image: mysql
    container_name: local_mysqldata
    restart: always
    ports:
      - "3306:3306"
    environment: 
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: db
      MYSQL_USER: user
      MYSQL_PASSWORD: admin
    volumes:
    - local_mysqldata:/var/lib/mysql
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_USER: user
      PMA_PASSWORD: admin
      PMA_HOSTS: db
      PMA_ARBITRARY: 1
volumes:
  local_mysqldata: 